# Generated by Django 2.0.1 on 2018-07-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('job_title', models.CharField(blank=True, max_length=40, null=True)),
                ('department', models.TextField(blank=True, max_length=40, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
