# Generated by Django 2.0.1 on 2018-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
