# Generated by Django 2.0.1 on 2018-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDirectory', '0003_auto_20180731_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
